### ISSUE TITLE
aldryn project setup does not pull base.css

### ISSUE THREAD

**Issue by quater** [divio/divio-cli#156]
I am filing this here with `aldryn-client` since I encounter this problem while using `aldryn-client` but I have the feeling this problem is due to a bug at the Aldryn Cloud backend.

I am using `aldryn-client` on Linux since I don't really have a Windows machine at hand to run the Aldryn Desktop app.

After having run `aldryn project setup myprojectname` command, the project is successfully downloaded to my local Linux machine, apart of one file, the `base.css` file.

Due to this the website does not render locally. To fix this I have to run `sass base.scss ../../static/css/base.css` in order to generate the `base.css` file.

Note, I have only observed this problem while using the Aldryn Explorer Theme.

**Comment by stefanfoulis** [comment]
Hi @quater 
Sorry for the late reply here.
This is expected behaviour. The base.css file is built when the docker image is built, but it is placed inside the project folder. When developing locally the current folder on the host machine is mounted into the docker container so it is possible to directly edit files inside the container.
So once the project is run locally, the command to build the css has to be run again.
Hope this helps.
